### ISSUE TITLE
Caching Continuous Integration dependencies/artifacts

### ISSUE THREAD

**Issue by Slyces** [CharlyCst/zephyr#29]
This feature is mentioned in #25 and could be implemented on the current simple script we have as a way to get used to github workflows and their handling of compilation artifacts.

**Comment by Slyces** [comment]
This should be implemented by 482e60a and tested by 865f69f. However, cargo build doesn't seem to be cached, even though I put a cache for the target directory.

@CharlyCst might need to look into it. I leave the issue open for now.

**Comment by CharlyCst** [comment]
I think that we should review the priority of this issue, there is no real for caching in the CI right now.

I'm closing this issue for now, but I consider the CI a 100% success, congrats @Slyces 🎉
