### ISSUE TITLE
Language Keywords and Operators

### ISSUE THREAD

**Issue by Slyces** [CharlyCst/zephyr#8]
The language should provide a set of language keywords to cover the core functionalities.

This thread will gather and update the existing and/or planned keywords, along with future keywords that might be reserved for later use, but not implemented yet.

Associated commit/PR (for solved features) or issues (for planned or under discussion) will be stated for each functionality.

---
**Keywords:**
- [x] `if`
- [x] `else`
- [x] `let`
- [x] `call`
- [x] `return`
- [x] `for`
- [x] `while`
- [ ] `struct`
- [ ] `break`
- [ ] `...`
---
**Operators**
- [x] substraction `x - y`
- [x] addition `x + y`
- [x] unary negative `- x` (PR #11)
- [ ] ...

**Comment by CharlyCst** [comment]
We already missed updating this thread with the new `package`, `use` and `pub` keywords, we should ask ourselves if it is the right way to keep track of the language evolution. 

The `grammar.md` file is always kept up to date though, maybe we should rely on it instead, WDYT @Slyces ?
